
UPDATE public.teams SET name = CASE code
  WHEN 'ALG' THEN 'Argélia'
  WHEN 'ARG' THEN 'Argentina'
  WHEN 'AUS' THEN 'Austrália'
  WHEN 'AUT' THEN 'Áustria'
  WHEN 'BEL' THEN 'Bélgica'
  WHEN 'BRA' THEN 'Brasil'
  WHEN 'CMR' THEN 'Camarões'
  WHEN 'CAN' THEN 'Canadá'
  WHEN 'CPV' THEN 'Cabo Verde'
  WHEN 'COL' THEN 'Colômbia'
  WHEN 'CRO' THEN 'Croácia'
  WHEN 'CZE' THEN 'República Tcheca'
  WHEN 'DEN' THEN 'Dinamarca'
  WHEN 'ECU' THEN 'Equador'
  WHEN 'EGY' THEN 'Egito'
  WHEN 'ENG' THEN 'Inglaterra'
  WHEN 'FRA' THEN 'França'
  WHEN 'GER' THEN 'Alemanha'
  WHEN 'GHA' THEN 'Gana'
  WHEN 'IRN' THEN 'Irã'
  WHEN 'ITA' THEN 'Itália'
  WHEN 'CIV' THEN 'Costa do Marfim'
  WHEN 'JPN' THEN 'Japão'
  WHEN 'JOR' THEN 'Jordânia'
  WHEN 'MEX' THEN 'México'
  WHEN 'MAR' THEN 'Marrocos'
  WHEN 'NED' THEN 'Países Baixos'
  WHEN 'NGA' THEN 'Nigéria'
  WHEN 'NOR' THEN 'Noruega'
  WHEN 'PAR' THEN 'Paraguai'
  WHEN 'POL' THEN 'Polônia'
  WHEN 'POR' THEN 'Portugal'
  WHEN 'QAT' THEN 'Catar'
  WHEN 'KSA' THEN 'Arábia Saudita'
  WHEN 'SCO' THEN 'Escócia'
  WHEN 'SEN' THEN 'Senegal'
  WHEN 'SRB' THEN 'Sérvia'
  WHEN 'RSA' THEN 'África do Sul'
  WHEN 'KOR' THEN 'Coreia do Sul'
  WHEN 'ESP' THEN 'Espanha'
  WHEN 'SWE' THEN 'Suécia'
  WHEN 'SUI' THEN 'Suíça'
  WHEN 'TUN' THEN 'Tunísia'
  WHEN 'TUR' THEN 'Turquia'
  WHEN 'URU' THEN 'Uruguai'
  WHEN 'USA' THEN 'Estados Unidos'
  WHEN 'UZB' THEN 'Uzbequistão'
  WHEN 'VEN' THEN 'Venezuela'
  ELSE name
END;
